### ISSUE TITLE
Data reliability ?

### ISSUE THREAD

**Issue by drraghuram** [thejeshgn/cpcb_bangalore#1]
Hi, first of all thanks very much for this initiative of making this data accessible in a good format. I am not sure the question I have is actually an issue. In the data.csv file,  I was looking at the data for just the SO2 column for the year 2015 for BTM Layout. Looking at the data, I noticed that the drop in the values are very steep. For example, row 13805 (12th Jan, 2015, timestamp: 4 am), the value of SO2 is 630.33, whereas the next value that is not a NaN is 3.1 (row number: 13808) on the 13th of January, timestamp: 12 p.m. This pattern of a very high drop buffered by NaN values is rather strange. I just wanted to know if this is normal behaviour or are there any problems with the data? 

I know the reasons behind this kind of behaviour could be myriad, sensor problems, incorrect entries on the part of CPCB, etc. My question really boils down to whether the data on the CPCB website is correct? Can it be vouched for?

**Comment by thejeshgn** [comment]
- This is the data from CPCB. I can't really vouch for the accuracy of it.
- A lot of people have found issues with the data they publish before. Best would be to do a RTI
